server:
  port: 9191 # 设置后端服务的端口

spring:
  datasource: #数据源配置
    driver-class-name: com.mysql.jdbc.Driver # com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud-collection?serverTimezone=UTC
    username: root
    password: 123456
      # max-idle: 10
      # max-wait: 10000
      # min-idle: 5
      # initial-size: 5
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# mybatis-plus:
#   #指明mapper.xml扫描位置(classpath* 代表编译后类文件根目录)
#   mapper-locations: classpath*:xml/*.xml
#   #指明实体扫描(多个package用逗号或者分号分隔)
#   type-aliases-package: com.by.ccs.model
#   global-config:
#     #主键类型 0:数据库ID自增, 1:用户输入ID,2:全局唯一ID (数字类型唯一ID), 3:全局唯一ID UUID
#     id-type: 0
#     #字段策略(拼接sql时用于判断属性值是否拼接) 0:忽略判断,1:非NULL判断,2:非空判断
#     field-strategy: 2
#     #驼峰下划线转换含查询column及返回column(column下划线命名create_time，返回java实体是驼峰命名createTime，开启后自动转换否则保留原样)
#     db-column-underline: true
#     #是否动态刷新mapper
#     refresh-mapper: false
#     #数据库大写命名下划线转换
#     #capital-mode: true

